package jts.gameserver.skills;

public enum SkillTargetType
{
	// none
	TARGET_EVENT,
	TARGET_COMMCHANNEL,

	// area of effect (w/o target)
	TARGET_AURA,
	TARGET_MULTIFACE_AURA,
	TARGET_ALLY,
	TARGET_CLAN,
	TARGET_CLAN_ONLY,
	TARGET_PARTY,
	TARGET_PARTY_NOT_SELF,

	// area of effect
	TARGET_AREA,
	TARGET_AREA_AIM_CORPSE,
	TARGET_MULTIFACE,
	TARGET_TUNNEL,

	// summoned creatures(self only)
	TARGET_PET,

	// servitor aura
	TARGET_PET_AURA,

	// single
	TARGET_CORPSE,
	TARGET_CORPSE_PLAYER,
	TARGET_HOLY,
	TARGET_FLAGPOLE,
	TARGET_NONE,
	TARGET_ITEM,
	TARGET_ONE,
	TARGET_PARTY_ONE,
	TARGET_OWNER,
	TARGET_ENEMY_PET,
	TARGET_ENEMY_SUMMON,
	TARGET_ENEMY_SERVITOR,
	TARGET_SELF,
	TARGET_UNLOCKABLE,
	TARGET_CHEST,
	TARGET_FEEDABLE_BEAST,
	TARGET_SIEGE;
}